services:
  top.api:
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: "linux/amd64"
    image: did82/top-api
    container_name: top-api
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./.env:/app/.env