name: Testing

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Node.js 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x
            - name: Install dependencies
              uses: bahmutov/npm-install@v1
            - name: Run linter
              run: npm run lint
    run-unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Node.js 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x
            - name: Install dependencies
              uses: bahmutov/npm-install@v1
            - name: Run tests
              run: npm run test
    run-e2e-tests:
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            JWT_SECRET: 'test'
        steps:
            - uses: actions/checkout@v3
            - name: Node.js 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x
            - name: Install dependencies
              uses: bahmutov/npm-install@v1
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
            - name: Prisma generate
              run: npx prisma generate
            - name: Run tests
              run: npm run test:e2e
    build:
        runs-on: ubuntu-latest
        needs: [lint, run-unit-tests, run-e2e-tests]
        steps:
            - uses: actions/checkout@v3
            - name: Publish to Registry
              uses: elgohr/Publish-Docker-Github-Action@v5
              with:
                  registry: docker.pkg.github.com
                  name: docker.pkg.github.com/Did82/purpleschool-nestjs-top-api
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  tags: 'develop'
